### ISSUE TITLE
Rule doesnt work for some articles

### ISSUE THREAD

**Issue by shawnw1** [gioxx/xfiles#17]
**Hey there**, i was wondering if it would be possible to update the rules for a news website please. It is www.winnipegfreepress.com.
unfortunately it does not seem to hide the paywall anymore, but it used to.

**Exmaple URL:** https://www.winnipegfreepress.com/local/2022/08/13/university-student-mom-grateful-for-camp-support
**Filter used:** https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt (**202208130349**).

Thank you for any time spent getting this rule working again :)
Shawn W.

**Comment by gioxx** [comment]
Hi @shawnw1 , I can read the full article you have linked using X Files experimental (with the same paywall filters grabbed from stable module).

![immagine](https://user-images.githubusercontent.com/1768601/185335528-98ea02ae-a071-49d9-a257-79b6f89ce5e1.png)

Please check again, thanks.

**Comment by shawnw1** [comment]
Sorry it took forever to get back. I completely forgot about it and I’m truly sorry :(. I’m hoping your still willing to help :). 

Here is a screen shot of the page:
![9394C92A-36B4-40F0-81B0-FE7031A65634](https://user-images.githubusercontent.com/6869713/192082332-c6569f2f-a857-4a0c-a64d-b11f960f12f9.png)

the url was: https://www.winnipegfreepress.com/arts-and-life/entertainment/arts/2022/09/23/arts-and-minds-2


The filter I’m using is the experimental (unstable):
![B7CF8020-5F31-44D4-9DCA-9998AF0CE1A4](https://user-images.githubusercontent.com/6869713/192082188-b6fb89e3-950b-4c06-8389-3116351a76fb.png)

Like always, I appreciate any help you may have for me. 


Shawn M. Wiebe

**Comment by gioxx** [comment]
Ciao @shawnw1, no problem.
I think the problem is on your side and with your device. I don't have an iPhone to test the webpage you have linked but there are two test I've maked on my MacBook and my OnePlus with Firefox, uBlock + experimental list.

This is the screenshot I have taken on PC: https://imagehosting.altervista.org/images/2022/09/24/f0486d1d7f13dedeb7a5d58b2cbb2141.png

And the other one captured on my Android smartphone: https://imagehosting.altervista.org/images/2022/09/24/64c5bec60970f280684eaba2fa3ca483.jpg

Honestly I don't understand why the same list is not working on iOS and your configuration. What is the extension you are using to filter your navigation?
